FROM mysql:8.0.43

# 安装 OpenJDK 17（Red Hat 系系统使用 yum 命令）
RUN yum update -y && \
    yum install -y java-17-openjdk-devel && \
    yum clean all && \
    rm -rf /var/cache/yum/*  # 清理缓存减小镜像体积

# 设置 JAVA_HOME 环境变量（Red Hat 系中 JDK 默认安装路径）
ENV JAVA_HOME=/usr/lib/jvm/java-17-openjdk
ENV PATH=$JAVA_HOME/bin:$PATH

# MySQL 配置
ENV MYSQL_ROOT_PASSWORD=20041123zZ@

# 复制 SQL 初始化文件
COPY database-schema.sql /docker-entrypoint-initdb.d/

# 复制 Java 应用
WORKDIR /app
COPY ./target/alumni-backend-1.0.0.jar /app/app.jar

# 启动脚本（确保同时启动 MySQL 和 Java 应用）
COPY start.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/start.sh
CMD ["start.sh"]