server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: hd-alumni-backend
  
  datasource:
#    url: jdbc:mysql://mysql:3306/hd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
#    username: hd
#    password: 20041123zZ@
    url: jdbc:mysql://mysql:3306/hd?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 20041123zZ@

    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000  # 連接超時時間，30秒
      maximum-pool-size: 10      # 最大連接池大小
      minimum-idle: 5            # 最小空閒連接數
      idle-timeout: 600000       # 空閒連接超時時間，10分鐘
      max-lifetime: 1800000      # 連接最大生存時間，30分鐘
      connection-test-query: SELECT 1  # 連接測試查詢
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    open-in-view: false
    
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      
  jackson:
    time-zone: Asia/Shanghai
    date-format: yyyy-MM-dd HH:mm:ss

# JWT配置
jwt:
  secret: hd-alumni-system-jwt-secret-key-2024-secure-key-for-jwt-token-generation-with-sufficient-length
  expiration: 86400000 # 24小时

# 文件上传配置
file:
  upload:
    path: ./uploads/
    max-size: 5242880 # 5MB
    allowed-types: jpg,jpeg,png,pdf

# 日志配置
logging:
  level:
    com.hd: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"